# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fa5504ad93868bc01c243d249810f541a40a5e01974a7811eceb45a8b4d18a150b0ab5dee7c74ff0ecb5faa753edbe22a156ebdfb6a5b03ba6a62dd5d771e59

test:
  secret_key_base: 0ff571f204d0d62dbda730405fbae7d1da0cfe5f7e257132ee7eddd768a89393ef5496e10685ca672376a4e2479ea43d97181fd32a126cdab39e6302ec1d00b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
